id: A319833A1
title: Brief Dhāraṇī of Glorious Vajraṇakhī
type: translation
pechas:
- IFE4764DF
- I32129339
- I55D77FD4
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:46:33.121308
  last_modified_at: 2023-01-04 12:46:33.121314
  collections:
  - Karma Chakme Series
  - Works of Tibetan Masters
alignment_to_base:
  IFE4764DF/A01B: '0402'
  I32129339/8D61: '0402'
  I55D77FD4/9372: '0402'
